:PROPERTIES:
:header-args: :session init :tangle init.el
:END:
#+title: Emacs Config File
#+author: Camilla A.
#+startup: overview


* Introduction.
Welcome to my config file.
You're welcome to use any bits of this if you want to, but I can't promise that it will work :) .

This is a [[https://en.wikipedia.org/wiki/Literate_programming][literate file]], that is, the program it documents is generated from this file -- I never edit the source file directly, only this file.
The file can be tangled (IE the source code can be written into [[file:init.el][init.el]]) by running
#+begin_src elisp :tangle no
  (org-babel-tangle)
#+end_src

Note that specific bits of code can be ignored by the tangling, such as the above.
I prefer this approach to programming, because I always aim to writing programs to me is first and foremost, an art.
Thus, I want people to be able to actually read my work.


* Package Management

This does 2 things:
- disable the standard package system starting
- bootstrap [[https://github.com/radian-software/straight.el][straight.el]]

Straight is a package manager for Emacs, and I prefer it to the standard one.
It lets me clone packages directly from git repos, which I prefer to the standard method.
#+begin_src elisp
  (setq package-enable-at-startup nil)

  (defvar bootstrap-version)
  (let ((bootstrap-file
  	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
  	(bootstrap-version 6))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
  	  (url-retrieve-synchronously
  	   "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
  	   'silent 'inhibit-cookies)
  	(goto-char (point-max))
  	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t
        use-package-always-ensure nil)
#+end_src


From this point onwards, this document will separated into two sections: Reading, and Writing.


* Reading
#+begin_src elisp
  (use-package magit)
#+end_src


I use a collection of themes called [[https://github.com/protesilaos/ef-themes][ef-themes]], created by Prot.
I also like to disable the tool bar, menu bar, and scroll bar, because I work almost entirely from the keyboard, and find them distracting.
#+begin_src elisp
  (use-package ef-themes
    :defer nil
    :config
    (load-theme 'ef-symbiosis t))

  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

* Writing
As I am a lisp programmer, paredit is essential for me.
#+begin_src elisp
  (use-package paredit
    :hook ((emacs-lisp-mode . enable-paredit-mode)))
#+end_src

