:PROPERTIES:
:header-args: :session init :tangle init.el
:END:
#+title: Emacs Config File
#+author: Camilla A.
#+startup: overview


* Introduction
Welcome to my config file.
You're welcome to use any bits of this if you want to, but I can't promise that it will work :) .

This is a [[https://en.wikipedia.org/wiki/Literate_programming][literate file]], that is, the program it documents is generated from this file -- I never edit the source file directly, only this file.
The file can be tangled (IE the source code can be written into [[file:init.el][init.el]]) by running
#+begin_src elisp :tangle no
  (org-babel-tangle)
#+end_src

Note that specific bits of code can be ignored by the tangling, such as the above.
I prefer this approach to programming, because I always aim to writing programs to me is first and foremost, an art.
Thus, I want people to be able to actually read my work.

* Package Management

This does 2 things:
- disable the standard package system starting
- bootstrap [[https://github.com/radian-software/straight.el][straight.el]]

Straight is a package manager for Emacs, and I prefer it to the standard one.
It lets me clone packages directly from git repos, which I prefer to the standard method.
#+begin_src elisp
  (setq package-enable-at-startup nil)

  (defvar bootstrap-version)
  (let ((bootstrap-file
  	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
  	(bootstrap-version 6))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
  	  (url-retrieve-synchronously
  	   "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
  	   'silent 'inhibit-cookies)
  	(goto-char (point-max))
  	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t
        use-package-always-ensure nil)
#+end_src


From this point onwards, this document will separated into two sections: Reading, and Writing.

* Reading
#+begin_src elisp
  (use-package magit)
#+end_src


I use a collection of themes called [[https://github.com/protesilaos/ef-themes][ef-themes]], created by Prot.
I also like to disable the tool bar, menu bar, and scroll bar, because I work almost entirely from the keyboard, and find them distracting.
#+begin_src elisp
  (use-package ef-themes
    :defer nil
    :config
    (load-theme 'ef-symbiosis t))

  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src

* Writing
As I am a lisp programmer, ~paredit~ is essential for me.
~paredit~ does "electric brackets", which for me at least, makes lisp feel completely natural, more so than any other language for thinking, in most cases at least.
#+begin_src elisp
  (use-package paredit
    :hook ((emacs-lisp-mode . enable-paredit-mode)
  	 (clojure-mode    . enable-paredit-mode))
    :after (cider))
#+end_src

~rainbow-delimiters~ is another really useful one.
It (as the name would imply) puts pretty colours onto the brackets, which makes lisp /really/ easy to read.
Paired with ~paredit~, this makes lisp a breeze.

#+begin_src elisp
  (use-package rainbow-delimiters
    :defer nil
    :hook ((emacs-lisp-mode . rainbow-delimiters-mode)
  	 (clojure-mode    . rainbow-delimiters-mode))
    :after (cider))
#+end_src

[[https://cider.mx/][Cider]] is a package for Clojure (my beloved <3), which extends Emacs support for it.
It boosts the interactivity for Clojure, so that we can do lisp in the most enjoyable way possible.

It gives:
- a REPL (Read Evaluate Print Loop), that supports stuff like [[https://leiningen.org/][Leiningen]]
- a really good debugger
- definition look ups
- good support for testing

And so much more that I love.

#+begin_src elisp
  (use-package cider)
#+end_src


[[https://rocq-prover.org/][Rocq]] (formally coq)
#+begin_src elisp
  (use-package proof-general)
#+end_src

I am bad at spelling.
I still think it's important though, so I want to keep ~flyspell~ up for when I'm writing in ~org mode~.
#+begin_src elisp
  ;(add-hook org-mode-hook flyspell-mode)

#+end_src
