:PROPERTIES:
:header-args: :session init :tangle init.el
:END:
#+title: Emacs Config File
#+author: Camilla A.
#+startup: overview


* Introduction
Welcome to my config file.
You're welcome to use any bits of this if you want to, but I can't promise that it will work :) .

This is a [[https://en.wikipedia.org/wiki/Literate_programming][literate file]], that is, the program it documents is generated from this file -- I never edit the source file directly, only this file.
The file can be tangled (IE the source code can be written into [[file:init.el][init.el]]) by running
#+begin_src elisp :tangle no
  (org-babel-tangle)
#+end_src

Alternatively, the elisp file this tangles to is also in this repo, for easy loading, in case you want to use my config (for some reason).
Note that specific bits of code can be ignored by the tangling, such as the above.
I prefer this approach to programming, because I always aim to writing programs to me is first and foremost, an art.
Thus, I want people to be able to actually read my work.

* Package Management

This does 2 things:
- disable the standard package system starting
- bootstrap [[https://github.com/radian-software/straight.el][straight.el]]

Straight is a package manager for Emacs, and I prefer it to the standard one.
It lets me clone packages directly from git repos, which I prefer to the standard method.
#+begin_src elisp
  (setq package-enable-at-startup nil)

  (defvar bootstrap-version)
  (let ((bootstrap-file
  	 (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
  	(bootstrap-version 6))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
  	  (url-retrieve-synchronously
  	   "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
  	   'silent 'inhibit-cookies)
  	(goto-char (point-max))
  	(eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t
        use-package-always-ensure nil)
#+end_src


From this point onwards, this document will separated into two sections: Reading, and Writing.

* Reading
[[https://magit.vc/][Magit]] is an amazing git porcelain.
#+begin_src elisp
  (use-package magit)
#+end_src


I use a collection of themes called [[https://github.com/protesilaos/ef-themes][ef-themes]], created by Prot.
I also like to disable the tool bar, menu bar, and scroll bar, because I work almost entirely from the keyboard, and find them distracting.
#+begin_src elisp
  (use-package ef-themes
    :defer nil
    :config
    (load-theme 'ef-symbiosis t))

  (tool-bar-mode -1)
  (menu-bar-mode -1)
  (scroll-bar-mode -1)
#+end_src


[[https://github.com/skeeto/elfeed][elfeed]] is a [[https://en.wikipedia.org/wiki/Rss][RSS]] reader for Emacs.
It is the best RSS reader I have ever used (which is admittedly a rather short list); it's got some really good tagging and searching filters, and far more importantly, I can easily extend it with elisp.
As it would happen, I have a few extra procedures written for it.
#+begin_src elisp
  (use-package elfeed
    :defer t
    :bind ("C-c e" . elfeed)
    :config
    (setq elfeed-feeds
  	  '(("https://planet.emacslife.com/atom.xml" blog emacs)
  	    ("https://summeremacs.github.io/posts/index.xml" blog emacs)
  	    ("https://xkcd.com/rss.xml" comic)
  	    ("https://www.smbc-comics.com/comic/rss" comic)
  	    ("https://www.monkeyuser.com/index.xml" comic)
  	    ("https://archlinux.org/feeds/news/" arch linux tech)
  	    ("https://wolfgirl.dev/blog/rss.xml" blog tech prog)
  	    ("https://izzys.casa/index.xml" blog tech prog)
  	    ("https://faultlore.com/blah/rss.xml" blog tech prog)
  	    ("https://welltypedwit.ch/rss.xml" tech blog)
  	    ("https://feeds.bbci.co.uk/news/bbcindepth/rss.xml" news bbc)
  	    ("https://www.quantamagazine.org/feed/" sci news)
  	    ("https://feeds.libsyn.com/499093/rss" tech podcast)
  	    ("http://hackaday.libsyn.com/rss" tech podcast)
  	    ("https://rustacean-station.org/podcast.rss" tech prog podcast)
  	    ("https://risky.biz/feeds/risky-business-news/" tech security podcast)
  	    ("https://churchofturing.github.io/feed.xml" tech blog)
  	    ;; Leadhead
  	    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC3_kehZbfRz-KrjXIqeIiPw" blog video)
  	    ;; Wendigoon
  	    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC3cpN6gcJQqcCM6mxRUo_dA" video spooky)
  	    ;; ABSTRACT
  	    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCIPfjC8FVLdul4-35JekB1g" video spooky)
  	    ;; SOG
  	    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCtMVHI3AJD4Qk4hcbZnI9ZQ" video blog)
  	    ;; Philosophy Tube
  	    ("https://www.youtube.com/feeds/videos.xml?channel_id=UC2PA-AKmVpU6NKCGtZq_rKQ" video phil)
  	    ("https://www.youtube.com/feeds/videos.xml?channel_id=UCctWUfejRybO1cCT6DmIRqQ" video speedrun))))
#+end_src

~cam/elfeed-remove-iplayer~ is a really disgusting procedure, that removes iplayer and sounds RSS entries from my feed.
There is defiantly a more elegant way to do this.
However, for now this works.

Literally all that it does is, first look at all bbc things that don't have article in the title somewhere, then just mark everything still there as read.
As said, bad solution.
#+begin_src elisp
  (defun cam/elfeed-remove-iplayer ()
    "I don't want iplayer or sounds from bbc,
  just the articles. This marks them as read."
    (interactive)
    (let ((new-filter "@1-month-ago +unread +bbc !article"))

      (setq elfeed-search-filter new-filter)
      (elfeed-search-update :force)
      (mark-whole-buffer)
      (elfeed-search-untag-all-unread)
      (elfeed-search-clear-filter)
      (message "BBC iplayer stuff removed.")))

#+end_src

#+begin_src elisp
  (global-set-key (kbd "C-c a") 'org-agenda)
#+end_src

* Writing
As I am a lisp programmer, ~paredit~ is essential for me.
~paredit~ does "electric brackets", which for me at least, makes lisp feel completely natural, more so than any other language for thinking, in most cases at least.
#+begin_src elisp
  (use-package paredit
    :hook ((emacs-lisp-mode . enable-paredit-mode)
  	 (clojure-mode    . enable-paredit-mode))
    :after (cider))
#+end_src

~rainbow-delimiters~ is another really useful one.
It (as the name would imply) puts pretty colours onto the brackets, which makes lisp /really/ easy to read.
Paired with ~paredit~, this makes lisp a breeze.

#+begin_src elisp
  (use-package rainbow-delimiters
    :defer nil
    :hook ((emacs-lisp-mode . rainbow-delimiters-mode)
  	 (clojure-mode    . rainbow-delimiters-mode))
    :after (cider))
#+end_src

[[https://cider.mx/][Cider]] is a package for Clojure (my beloved <3), which extends Emacs support for it.
It boosts the interactivity for Clojure, so that we can do lisp in the most enjoyable way possible.

It gives:
- a REPL (Read Evaluate Print Loop), that supports stuff like [[https://leiningen.org/][Leiningen]]
- a really good debugger
- definition look ups
- good support for testing

And so much more that I love.

#+begin_src elisp
  (use-package cider)
#+end_src


[[https://rocq-prover.org/][Rocq]] (formally coq)
#+begin_src elisp
  (use-package proof-general)
#+end_src

Haskell is a beautiful declarative, lazy, and functional programming language.
#+begin_src elisp
  (use-package haskell-mode)
#+end_src

I am bad at spelling.
I still think it's important though, so I want to keep ~flyspell~ up for when I'm writing in ~org mode~.
#+begin_src elisp
  ;(add-hook org-mode-hook flyspell-mode)

#+end_src
